<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Client;
use AppBundle\Repository\RendezVousRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{

    public function getAllByEspece(String $espece)
    {
        return $this->createQueryBuilder('c')
            ->join('c.espece', 'e')
            ->where('e.nom = :nom')
            ->setParameter('nom', $espece)
            ->getQuery()
            ->getResult();
    }
}
