<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocteurRepository extends EntityRepository
{

    public function getByClientEspece(int $idEspece)
    {
        $qb = $this->createQueryBuilder('d')
            ->join('d.especes', 'de')
            ->where('de.id = :id')
            ->setParameter('id', $idEspece);

        return $qb;
    }
}
