app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /app
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app/client/
        permanent: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"